name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run setup script
      run: python3 scripts/setup.py --skip-upgrade

    - name: Build the PDF
      run: python3 scripts/build_pdf.py

    - name: Archive built pdf
      if: success()
      run: |
        mkdir -p artifacts
        cp output/main.pdf artifacts/
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-pdf
        path: artifacts